# plot aggregate signals

TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/FOS_MA0476.1/beds/FOS_MA0476.1_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/FOS_MA0476.1_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x
TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/FOSL1_MA0477.2/beds/FOSL1_MA0477.2_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/FOSL1_MA0477.2_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x
TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/FOSL2_MA0478.1/beds/FOSL2_MA0478.1_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/FOSL2_MA0478.1_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x
TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/JUN_MA0488.1/beds/JUN_MA0488.1_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/JUN_MA0488.1_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x
TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/JUNB_MA0490.2/beds/JUNB_MA0490.2_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/JUNB_MA0490.2_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x
TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/JUND_MA0491.2/beds/JUND_MA0491.2_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/JUND_MA0491.2_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x
TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/SNAI1_MA1558.1/beds/SNAI1_MA1558.1_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/SNAI1_MA1558.1_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x
TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/ETS1_MA0098.3/beds/ETS1_MA0098.3_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/ETS1_MA0098.3_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x
TOBIAS PlotAggregate --TFBS results/pval005/fibro_myeloid/ZEB1_MA0103.3/beds/ZEB1_MA0103.3_all.bed --signals results/*_footprints.bw --signal-labels Fibroblasts Myeloid B_Cells CytoT_NK_ILC Epithelial Plasma Stromal T_Lymphoid --output results/plotaggregate_supp/ZEB1_MA0103.3_footprints_comparison_all.pdf --share_y both --plot_boundaries --signal-on-x

# generate a bed file containing all binding sites of all JASPAR motifs

cat results/nonbcell_bcell/*/beds/*_all.bed > resources/all_binding_sites.bed

# plot tracks (colors can be adjusted)

TOBIAS PlotTracks --bigwigs results/*_footprints.bw --regions resources/CHI3L1_promoter.bed --sites resources/all_binding_sites.bed --gtf tmp/genes.gtf --colors darkblue red red red darkblue darkblue darkblue red --outdir tmp/plottrack_kyle_test/
TOBIAS PlotTracks --bigwigs results/*_footprints.bw --regions resources/OSM_promoter.bed --sites resources/all_binding_sites.bed --gtf tmp/genes.gtf --colors darkblue red red red darkblue darkblue darkblue red --outdir tmp/plottrack_kyle_test/
TOBIAS PlotTracks --bigwigs results/*_footprints.bw --regions resources/PTGER4_promoter.bed --sites resources/all_binding_sites.bed --gtf tmp/genes.gtf --colors darkblue red red red darkblue darkblue darkblue red --outdir tmp/plottrack_kyle_test/
TOBIAS PlotTracks --bigwigs results/*_footprints.bw --regions resources/PTGER4.bed --sites resources/all_binding_sites.bed --gtf tmp/genes.gtf --colors darkblue red red red darkblue darkblue darkblue red --outdir tmp/plottrack_kyle_test/
TOBIAS PlotTracks --bigwigs results/*_footprints.bw --regions resources/LACC1_promoter.bed --sites resources/all_binding_sites.bed --gtf tmp/genes.gtf --colors darkblue red red red darkblue darkblue darkblue red --outdir tmp/plottrack_kyle_test/
TOBIAS PlotTracks --bigwigs results/*_footprints.bw --regions resources/LACC1.bed --sites resources/all_binding_sites.bed --gtf tmp/genes.gtf --colors darkblue red red red darkblue darkblue darkblue red --outdir tmp/plottrack_kyle_test/
TOBIAS PlotTracks --bigwigs results/*_footprints.bw --regions resources/PLAU_promoter.bed --gtf resources/genes.gtf  --colors darkblue green red red red red red green --outdir results/plottracks_PLAU/
TOBIAS PlotTracks --bigwigs results/*_footprints.bw --regions resources/PLAUR_promoter.bed --gtf resources/genes.gtf  --colors darkblue darkblue green green green green red darkblue --outdir results/plottracks_PLAU/
